version: 2.1

executors:
  node12:
    docker:
      - image: circleci/node:12.16.3

commands:
  build:
    description: Install dependencies and build the project
    steps:
      - run: 
          name: Install exact dependencies
          command: npm install -E
      - run: 
          name: Build the website
          command: npm run build

jobs:
  build-and-test:
    executor: node12
    steps:
      - checkout
      - build

  build-test-and-deploy:
    executor: node12
    steps:
      - checkout
      - build
      - run: 
          name: Pack the website in a .tar.gz
          command: tar czf static_website.tar.gz -C public .
      - store_artifacts:
          path: static_website.tar.gz
      - run: 
          name: Trigger a deploy of the deploy project passing the desired environment/location to deploy to
          command: 'curl --header "Content-Type: application/json" --data "{\"build_parameters\": {\"deploy_location\": \"$CIRCLE_BRANCH\", \"CIRCLE_JOB\": \"deploy\"}}" --request POST "https://circleci.com/api/v1.1/project/github/PokeAPI/deploy/tree/test-staging?circle-token=$CIRCLECI_API_TOKEN"' # TODO: replace `test-staging` with `master`

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build-and-test
      - build-test-and-deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - staging
